services:
  api:
    build:
      dockerfile: docker/api/Dockerfile
      context: .
    volumes:
      - .:/api
    depends_on:
      - postgres
    command: sh -c "python3 -B -m app.main"
    ports:
      - "${API_PORT}:${API_PORT}"

  migrations:
    build:
      dockerfile: docker/migrations/Dockerfile
    volumes:
      - ./migrations/versions:/migrations/migrations/versions
    depends_on:
      - api
      - postgres
    command: sh -c "alembic upgrade head"
    restart: on-failure

  postgres:
    image: postgres:14.2
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"

  postgres-airflow:
    image: postgres:14.2
    environment:
      POSTGRES_USER: ${AIRFLOW_DB_USERNAME}
      POSTGRES_PASSWORD: ${AIRFLOW_DB_PASS}
      POSTGRES_DB: ${AIRFLOW_DB_NAME}

  airflow-init:
    image: apache/airflow:latest
    environment:
      AIRFLOW__CORE__EXECUTOR: ${AIRFLOW_CORE_EXECUTOR}
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: ${AIRFLOW_CORE_SQLALC_CONN}
      AIRFLOW__CORE__LOAD_EXAMPLES: ${AIRFLOW_CORE_LOAD_EX}
    volumes:
      - ${AIRFLOW_CORE_PATH}/dags:/opt/airflow/dags
      - ${AIRFLOW_CORE_PATH}/logs:/opt/airflow/logs
      - ${AIRFLOW_CORE_PATH}/plugins:/opt/airflow/plugins
    entrypoint: sh -c 'airflow db init'

  airflow-webserver:
    image: apache/airflow:latest
    environment:
      AIRFLOW__CORE__EXECUTOR: ${AIRFLOW_CORE_EXECUTOR}
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: ${AIRFLOW_CORE_SQLALC_CONN}
    ports:
      - "${AIRFLOW_DB_PORTS}:8080"
    depends_on:
      - postgres
      - airflow-init
    volumes:
      - ${AIRFLOW_CORE_PATH}/dags:/opt/airflow/dags
      - ${AIRFLOW_CORE_PATH}/logs:/opt/airflow/logs
      - ${AIRFLOW_CORE_PATH}/plugins:/opt/airflow/plugins
    command: "airflow webserver"

  airflow-scheduler:
    image: apache/airflow:latest
    environment:
      AIRFLOW__CORE__EXECUTOR: ${AIRFLOW_CORE_EXECUTOR}
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: ${AIRFLOW_CORE_SQLALC_CONN}
    depends_on:
      - postgres
      - airflow-init
    volumes:
      - ${AIRFLOW_CORE_PATH}/dags:/opt/airflow/dags
      - ${AIRFLOW_CORE_PATH}/logs:/opt/airflow/logs
      - ${AIRFLOW_CORE_PATH}/plugins:/opt/airflow/plugins
    command: "airflow scheduler"
