services:
  api:
    build:
      dockerfile: docker/api/Dockerfile
      context: .
    volumes:
      - ./app/:/api/app/
    depends_on:
      - postgres
    command: sh -c "python3 -B -m app.main"
    ports:
      - "${API_PORT}:${API_PORT}"
    networks:
      - api-network

  migrations:
    build:
      context: .
      dockerfile: docker/migrations/Dockerfile
    volumes:
      - ./migrations/versions:/migrations/migrations/versions
    depends_on:
      - api
      - postgres
    command: sh -c "alembic upgrade head"
    restart: on-failure
    networks:
      - api-network

  postgres:
    image: postgres:14.2
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - api-network
      - airflow-network

  postgres-airflow:
    image: postgres:13
    environment:
      POSTGRES_USER: ${AIRFLOW_DB_USERNAME}
      POSTGRES_PASSWORD: ${AIRFLOW_DB_PASS}
      POSTGRES_DB: ${AIRFLOW_DB_NAME}
    networks:
      - airflow-network

  airflow-init:
    image: ${AIRFLOW_VERSION}
    environment:
      AIRFLOW__CORE__EXECUTOR: ${AIRFLOW_CORE_EXECUTOR}
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: ${AIRFLOW_CORE_SQLALC_CONN}
      AIRFLOW__CORE__LOAD_EXAMPLES: ${AIRFLOW_CORE_LOAD_EX}
      AIRFLOW__WEBSERVER__SECRET_KEY: ${AIRFLOW__WEBSERVER__SECRET_KEY}
    depends_on:
      - postgres-airflow
    volumes:
      - ${AIRFLOW_CORE_PATH}/dags:/opt/airflow/dags
    entrypoint: sh -c 'airflow db init'
    restart: on-failure
    networks:
      - airflow-network

  airflow-webserver:
    build:
      context: .
      dockerfile: docker/airflow/Dockerfile
      args:
        AIRFLOW_VERSION: ${AIRFLOW_VERSION}
    environment:
      AIRFLOW__CORE__EXECUTOR: ${AIRFLOW_CORE_EXECUTOR}
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: ${AIRFLOW_CORE_SQLALC_CONN}
      AIRFLOW__WEBSERVER__SECRET_KEY: ${AIRFLOW__WEBSERVER__SECRET_KEY}
    ports:
      - "${AIRFLOW_DB_PORTS}:8080"
    depends_on:
      - postgres-airflow
      - airflow-init
    volumes:
      - ${AIRFLOW_CORE_PATH}/dags:/opt/airflow/dags
    command: "airflow webserver"
    networks:
      - airflow-network

  airflow-scheduler:
    image: ${AIRFLOW_VERSION}
    environment:
      AIRFLOW__CORE__EXECUTOR: ${AIRFLOW_CORE_EXECUTOR}
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: ${AIRFLOW_CORE_SQLALC_CONN}
      POSTGRES_CONN_LINK: ${POSTGRES_CONN_LINK}
      AIRFLOW__WEBSERVER__SECRET_KEY: ${AIRFLOW__WEBSERVER__SECRET_KEY}
    depends_on:
      - postgres-airflow
      - airflow-init
    volumes:
      - ${AIRFLOW_CORE_PATH}/dags:/opt/airflow/dags
    command: "airflow scheduler"
    networks:
      - airflow-network

networks:
  airflow-network:
  api-network:
