version: "2"


services:
  # redis:
  #   image: redis:latest
  #   container_name: redis
  #   ports:
  #     - "6379:6379"
  #   restart: always

  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_DB: root5
      POSTGRES_USER: root5
      POSTGRES_PASSWORD: root5
      POSTGRES_HOST: localhost


      # POSTGRES_DB: ${DB}
      # POSTGRES_USER: ${USER}
      # POSTGRES_PASSWORD: ${PASSWORD}
    ports:
      - "5432:5432"

    env_file:
      - .env
  blog:
    build: .
    volumes:
      - .:/app
    command: python manage.py runserver localhost:8000
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
