# Generated by Django 4.2.5 on 2023-09-07 18:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('username', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1500)),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blog.usermodel')),
            ],
        ),
        migrations.CreateModel(
            name='PostLikesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog.postmodel')),
                ('who_likes', models.ManyToManyField(to='blog.usermodel')),
            ],
        ),
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                ('author', models.ManyToManyField(to='blog.usermodel')),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog.postmodel')),
            ],
        ),
    ]
